import { StoreCategory, StoreProduct } from "./product.model";

export const STORE_BRAND = {
  name: "AK Electricals",
  tagline: "Welcome to our market!",
  phone: "(+91) 8876900903",
  email: "akelectricalsbprd@gmail.com",
  address: "12 Industrial Estate, Pune, Maharashtra 411019",
  hours: "Mon - Sun / 9:00AM - 8:00PM",
  currency: "INR"
} as const;

export const STORE_CATEGORIES: StoreCategory[] = [
  {
    id: "cat-electronics",
    name: "Electronics",
    slug: "electronics",
    description: "Keyboards, PCs, headsets, phones, printers and more.",
    image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: "cat-switches",
    name: "Switches & Sockets",
    slug: "switches-sockets",
    description: "Modular plates and premium switch finishes.",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: "cat-lighting",
    name: "Lighting",
    slug: "lighting",
    description: "LED panels, battens and flood lights.",
    image: "https://images.unsplash.com/photo-1524484485612-18f1cec4a3b8?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: "cat-cables",
    name: "Wires & Cables",
    slug: "wires-cables",
    description: "FR house wires and control cables.",
    image: "https://images.unsplash.com/photo-1473341304170-971dccb5ce1e?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: "cat-switchgear",
    name: "Switchgear",
    slug: "switchgear",
    description: "MCBs, RCCBs and distribution boards.",
    image: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: "cat-fans",
    name: "Fans & Ventilation",
    slug: "fans-ventilation",
    description: "Ceiling and exhaust fans.",
    image: "https://images.unsplash.com/photo-1591488320449-011701bb6704?auto=format&fit=crop&w=800&q=80"
  }
];

/** Catalog patterned after Emporium /products/electronics plus AK Electricals stock. */
export const STORE_PRODUCTS: StoreProduct[] = [
  {
    id: "e1",
    sku: "EMP-KB-01",
    name: "Keyboard",
    slug: "keyboard",
    categoryId: "cat-electronics",
    brand: "Emporium",
    description: "Full-size membrane keyboard with quiet keys for office and retail counters.",
    price: 175,
    currency: "USD",
    unit: "pc",
    rating: 4.5,
    reviewCount: 4,
    inStock: true,
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=900&q=80",
    features: ["USB plug & play", "Spill-resistant deck", "Windows / macOS"]
  },
  {
    id: "e2",
    sku: "EMP-AIO-01",
    name: "PC All-in-One",
    slug: "pc-all-in-one",
    categoryId: "cat-electronics",
    brand: "Emporium",
    description: "Space-saving all-in-one desktop for POS desks and back-office work.",
    price: 2179.99,
    compareAtPrice: 2510,
    currency: "USD",
    unit: "pc",
    rating: 5,
    reviewCount: 8,
    inStock: true,
    badge: "sale",
    image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=900&q=80",
    features: ["23.8\" Full HD", "8 GB RAM", "256 GB SSD"]
  },
  {
    id: "e3",
    sku: "EMP-HS-01",
    name: "Headset",
    slug: "headset",
    categoryId: "cat-electronics",
    brand: "Emporium",
    description: "Over-ear stereo headset with boom mic for calls and support desks.",
    price: 30,
    currency: "USD",
    unit: "pc",
    rating: 4.5,
    reviewCount: 12,
    inStock: true,
    image: "https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=900&q=80",
    features: ["Noise-isolating cups", "Inline mute", "3.5 mm jack"]
  },
  {
    id: "e4",
    sku: "EMP-PB-01",
    name: "ProBook",
    slug: "probook",
    categoryId: "cat-electronics",
    brand: "Emporium",
    description: "Lightweight business laptop for field engineers and sales teams.",
    price: 1379.99,
    compareAtPrice: 1655,
    currency: "USD",
    unit: "pc",
    rating: 4.5,
    reviewCount: 6,
    inStock: true,
    badge: "sale",
    image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80",
    features: ["14\" display", "Backlit keyboard", "All-day battery"]
  },
  {
    id: "e5",
    sku: "EMP-PH-01",
    name: "Phone",
    slug: "phone",
    categoryId: "cat-electronics",
    brand: "Emporium",
    description: "Desk IP phone for reception and warehouse offices.",
    price: 476,
    currency: "USD",
    unit: "pc",
    rating: 5,
    reviewCount: 2,
    inStock: true,
    image: "https://images.unsplash.com/photo-1520923642038-b4259acecbd7?auto=format&fit=crop&w=900&q=80",
    features: ["PoE ready", "HD voice", "Multi-line display"]
  },
  {
    id: "e6",
    sku: "EMP-PR-01",
    name: "All-in-One Printer",
    slug: "all-in-one-printer",
    categoryId: "cat-electronics",
    brand: "Emporium",
    description: "Print, scan and copy for invoices and delivery challans.",
    price: 450,
    currency: "USD",
    unit: "pc",
    rating: 3.5,
    reviewCount: 4,
    inStock: true,
    image: "https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?auto=format&fit=crop&w=900&q=80",
    features: ["Wi-Fi", "ADF scanner", "Auto duplex"]
  },
  {
    id: "p1",
    sku: "AK-SW-16A-W",
    name: "16A Modular Switch",
    slug: "16a-modular-switch-white",
    categoryId: "cat-switches",
    brand: "AK Pro",
    description: "Heavy-duty 16A modular switch with flame-retardant body.",
    price: 89,
    compareAtPrice: 120,
    currency: "INR",
    unit: "pc",
    rating: 4.6,
    reviewCount: 128,
    inStock: true,
    badge: "sale",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=900&q=80",
    features: ["16A rated", "ISI marked", "Modular plate compatible"]
  },
  {
    id: "p2",
    sku: "AK-LED-PANEL-12",
    name: "12W Round LED Panel",
    slug: "12w-round-led-panel",
    categoryId: "cat-lighting",
    brand: "LumenAK",
    description: "Recessed 12W LED panel with high CRI driver.",
    price: 249,
    compareAtPrice: 329,
    currency: "INR",
    unit: "pc",
    rating: 4.8,
    reviewCount: 214,
    inStock: true,
    badge: "featured",
    image: "https://images.unsplash.com/photo-1524484485612-18f1cec4a3b8?auto=format&fit=crop&w=900&q=80",
    features: ["6500K", "2-year warranty", "Eye-comfort diffuser"]
  },
  {
    id: "p3",
    sku: "AK-WIRE-1.5-FR",
    name: "1.5 sq.mm FR House Wire",
    slug: "15-sqmm-fr-house-wire",
    categoryId: "cat-cables",
    brand: "AK Cable",
    description: "Annealed copper FR house wire, 90 m coil.",
    price: 1899,
    compareAtPrice: 2199,
    currency: "INR",
    unit: "coil",
    rating: 4.7,
    reviewCount: 96,
    inStock: true,
    badge: "sale",
    image: "https://images.unsplash.com/photo-1473341304170-971dccb5ce1e?auto=format&fit=crop&w=900&q=80",
    features: ["99.9% copper", "FR PVC", "Colour-coded"]
  },
  {
    id: "p4",
    sku: "AK-MCB-32A-SP",
    name: "32A Single Pole MCB",
    slug: "32a-sp-mcb-c-curve",
    categoryId: "cat-switchgear",
    brand: "AK Shield",
    description: "DIN-rail SP MCB C-curve for residential boards.",
    price: 189,
    currency: "INR",
    unit: "pc",
    rating: 4.5,
    reviewCount: 77,
    inStock: true,
    badge: "new",
    image: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=900&q=80",
    features: ["10kA", "C-curve", "ISI / IEC"]
  },
  {
    id: "p5",
    sku: "AK-FAN-BLDC-1200",
    name: "1200mm BLDC Ceiling Fan",
    slug: "1200mm-bldc-ceiling-fan",
    categoryId: "cat-fans",
    brand: "AeroAK",
    description: "Energy-efficient BLDC ceiling fan with remote.",
    price: 3499,
    compareAtPrice: 4299,
    currency: "INR",
    unit: "pc",
    rating: 4.9,
    reviewCount: 312,
    inStock: true,
    badge: "featured",
    image: "https://images.unsplash.com/photo-1591488320449-011701bb6704?auto=format&fit=crop&w=900&q=80",
    features: ["~28W", "Remote", "Reverse mode"]
  },
  {
    id: "p11",
    sku: "AK-BATTEN-20W",
    name: "20W LED Batten",
    slug: "20w-led-batten",
    categoryId: "cat-lighting",
    brand: "LumenAK",
    description: "Slim surface LED batten for shops and corridors.",
    price: 399,
    compareAtPrice: 499,
    currency: "INR",
    unit: "pc",
    rating: 4.7,
    reviewCount: 201,
    inStock: true,
    badge: "featured",
    image: "https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?auto=format&fit=crop&w=900&q=80",
    features: ["Flicker-free", "Surface kit", "Cool daylight"]
  }
];
